
# SPDX-FileCopyrightText: 2024 Arthur A. Gleckler
# SPDX-License-Identifier: MIT
* SRFI 2XX: In-source documentation

** TODO list

- Write SRFI 38 reader with support for extended syntax.
- Write the read-doc procedure (use SRFI 38 reader also?)
- Tie in to the package management SRFI to store documentation build
  configuration
- Specify scope attribute of attached documentation? (differentiating between
  documentation of a library vs. sublibraries vs. library contents)

** by Antero Mejr



keywords: [[https://srfi.schemers.org/?keywords=operating-system][Operating System]], [[https://srfi.schemers.org/?keywords=reader-syntax][Reader Syntax]]

This repository hosts [[https://srfi.schemers.org/srfi-2xx/][SRFI 2xx]]: In-source documentation, a [[https://srfi.schemers.org/][Scheme Request for Implementation]].

This SRFI is in /draft/ status.
See also [[/srfi-30/][SRFI 30: Nested Multi-line Comments]],  [[/srfi-138/][SRFI 138: Compiling Scheme programs to executables]], and [[/srfi-176/][SRFI 176: Version flag]].
The full documentation for this SRFI can be found in the [[https://srfi.schemers.org/srfi-2xx/srfi-2xx.html][SRFI Document]].

If you'd like to participate in the discussion of this SRFI, or report issues with it, please [[https://srfi.schemers.org/srfi-2xx/][join the SRFI-2xx mailing list]] and send your message there.

Thank you.

[[mailto:srfi-editors@srfi.schemers.org][The SRFI Editors]]
